In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

KNN для среднего чека

In [ ]:
df_average_bill = pd.read_csv("../../data/df_train_average_bill_encoded_scaled.csv")
df_average_bill.head()

,Средний чек,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час",month_sin,month_cos,pca_1,pca_2,pca_3,pca_4,Населенный пункт_fold_average_bill,Регион_fold_average_bill,"Дата открытия, категориальный_Новый","Дата открытия, категориальный_Открыт давно","Дата открытия, категориальный_Средний по возрасту","Торговая площадь, категориальный_Большой","Торговая площадь, категориальный_Маленький","Торговая площадь, категориальный_Очень большой","Торговая площадь, категориальный_Средний"
0,823.060390,-0.183291,-0.634931,-0.658506,0.29525,-8.660254e-01,0.500000,-0.647364,0.219085,0.058661,-1.24818,0.087335,-0.086181,0,0,1,0,0,0,1
1,859.361975,-0.183291,-0.634931,-0.658506,0.29525,5.000000e-01,-0.866025,-0.647364,0.219085,0.058661,-1.24818,0.087335,-0.086181,0,0,1,0,0,0,1
2,763.937766,-0.183291,-0.634931,-0.658506,0.29525,5.000000e-01,0.866025,-0.647364,0.219085,0.058661,-1.24818,0.087335,-0.086181,0,0,1,0,0,0,1
3,836.362309,-0.183291,-0.634931,-0.658506,0.29525,1.224647e-16,-1.000000,-0.647364,0.219085,0.058661,-1.24818,0.087335,-0.086181,0,0,1,0,0,0,1
4,845.257709,-0.183291,-0.634931,-0.658506,0.29525,-5.000000e-01,-0.866025,-0.647364,0.219085,0.058661,-1.24818,0.087335,-0.086181,0,0,1,0,0,0,1

In [ ]:
X = df_average_bill.drop("Средний чек", axis=1)
y = df_average_bill["Средний чек"]

print("Размер X:", X.shape)
print("Размер y:", y.shape)

Размер X: (232669, 19)
Размер y: (232669,)

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=56)

print("Train:", X_train.shape)
print("Test:", X_val.shape)

Train: (162868, 19)
Test: (69801, 19)

In [ ]:
knn = KNeighborsRegressor(n_jobs=-1)

param_grid = {
    "n_neighbors": list(range(1, 20))
}

gridsearch = GridSearchCV(
    estimator=knn,
    param_grid=param_grid,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=-1
)

gridsearch.fit(X_val, y_val)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(n_jobs=-1), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19]},
             scoring='neg_mean_absolute_error')

In [ ]:
print("Лучшие параметры:", gridsearch.best_params_)
print("Лучшее MAE на кросс-валидации:", -gridsearch.best_score_)

Лучшие параметры: {'n_neighbors': 1}
Лучшее MAE на кросс-валидации: 132.1471256669582

In [ ]:
knn_average_bill_best = gridsearch.best_estimator_

KNN для трафика

In [ ]:
df_traffic = pd.read_csv("../../data/df_train_traffic_encoded_scaled.csv")
df_traffic.head()

,Трафик,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час",month_sin,month_cos,pca_1,pca_2,pca_3,pca_4,Населенный пункт_fold_traffic,Регион_fold_traffic,"Дата открытия, категориальный_Новый","Дата открытия, категориальный_Открыт давно","Дата открытия, категориальный_Средний по возрасту","Торговая площадь, категориальный_Большой","Торговая площадь, категориальный_Маленький","Торговая площадь, категориальный_Очень большой","Торговая площадь, категориальный_Средний"
0,59662,-0.183291,-0.634931,-0.658506,0.29525,-8.660254e-01,0.500000,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
1,56674,-0.183291,-0.634931,-0.658506,0.29525,5.000000e-01,-0.866025,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
2,51488,-0.183291,-0.634931,-0.658506,0.29525,5.000000e-01,0.866025,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
3,56693,-0.183291,-0.634931,-0.658506,0.29525,1.224647e-16,-1.000000,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
4,58128,-0.183291,-0.634931,-0.658506,0.29525,-5.000000e-01,-0.866025,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1

In [ ]:
X = df_traffic.drop("Трафик", axis=1)
y = df_traffic["Трафик"]

print("Размер X:", X.shape)
print("Размер y:", y.shape)

Размер X: (232669, 19)
Размер y: (232669,)

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=56)

print("Train:", X_train.shape)
print("Test:", X_test.shape)

Train: (162868, 19)
Test: (69801, 19)

In [ ]:
parameters = {
    "n_neighbors": range(1, 10)
}

gridsearch_traffic = GridSearchCV(
    KNeighborsRegressor(),
    parameters,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=-1
)

gridsearch_traffic.fit(X_val, y_val)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'n_neighbors': range(1, 10)},
             scoring='neg_mean_absolute_error')

In [ ]:
print("Лучшие параметры:", gridsearch_traffic.best_params_)
print("Лучшее MAE на кросс-валидации:", gridsearch_traffic.best_score_)

Лучшие параметры: {'n_neighbors': 1}
Лучшее MAE на кросс-валидации: -5681.693872376569

In [ ]:
knn_traffic_best = gridsearch_traffic.best_estimator_